package com.codel.enumeration;

public enum Response {
	OK,
	
	EMAIL_NOT_FOND,
	FIRSTNAME_NOT_FOUND,
	LASTTNAME_NOT_FOUND,
	STREETNUMBER_NOT_FOUND,
	STREETTYPE_NOT_FOUND,
	STREETNAME_NOT_FOUND,
	CODEPOSTAL_NOT_FOUND,
	CITY_NOT_FOUND,
	COUNTRY_NOT_FOUND
}
